package schoolresult;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author SAHU COMPUTER
 */
public class MainPage extends javax.swing.JFrame {
    
    Connection conn=null;
    PreparedStatement pstmt,inser,delete,fetch,modify;
    ResultSet res;
    Statement st;
    int tot;
    String gr="";
    DbConnection dbc;
    //ListAll li = new ListAll();
    
    /**
     * Creates new form MainPage
     */
    /*public MainPage() {
        initComponents();
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");//oracle
             conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","akshat","akshat");//oracle
            System.out.println("gadha inside init");
            
            //con = DriverManager.getConnection("jdbc:ucanaccess://e:\\java akshat\\project\\mydb.accdb");//ms access
        // Class.forName("java.sql.Driver");// my  sql
        // con=DriverManager.getConnection("jdbc:mysql://localhost:3306/akshat","root","akshat");// my sql
            
        }
        catch(ClassNotFoundException | SQLException e)
        {
            JOptionPane.showMessageDialog(this,"Exception ",e.toString(),JOptionPane.ERROR_MESSAGE);
        }
    
    }*/
    public MainPage(){
        this.dbc=new DbConnection();
        this.conn=dbc.connect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtroll = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txteng = new javax.swing.JTextField();
        txthind = new javax.swing.JTextField();
        txtmts = new javax.swing.JTextField();
        txtsst = new javax.swing.JTextField();
        txtsci = new javax.swing.JTextField();
        totlabel = new javax.swing.JLabel();
        btnins = new javax.swing.JButton();
        btnrst = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        btntot = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnfetchall = new javax.swing.JButton();
        btnfetch = new javax.swing.JButton();
        btnmenu = new javax.swing.JButton();
        psfllabel = new javax.swing.JLabel();
        gradelabel = new javax.swing.JLabel();
        txtgrade = new javax.swing.JTextField();
        txtpsfl = new javax.swing.JTextField();

        jLabel10.setText("jLabel10");

        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(167, 149, 232));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jPanel1.setName("TItle section"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCHOOL RESULT MAKER");
        jLabel1.setAlignmentX(200.0F);
        jLabel1.setAlignmentY(100.0F);
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(249, 174, 163));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ROLL NUMBER : - ");

        jLabel3.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NAME : - ");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTER THE MARKS OF THE FOLLOWING SUBJECTS ");

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ENGLISH :-");

        jLabel6.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HINDI :-");

        jLabel7.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SOCIAL SCIENCE :-");

        jLabel9.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("MATHS :-");

        jLabel8.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SCIENCE :-");

        txtroll.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtroll.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        txtroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrollActionPerformed(evt);
            }
        });

        txtname.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        txteng.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txteng.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        txteng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtengActionPerformed(evt);
            }
        });

        txthind.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txthind.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        txthind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthindActionPerformed(evt);
            }
        });

        txtmts.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtmts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        txtmts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmtsActionPerformed(evt);
            }
        });

        txtsst.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtsst.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        txtsst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsstActionPerformed(evt);
            }
        });

        txtsci.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtsci.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        txtsci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsciActionPerformed(evt);
            }
        });

        totlabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        totlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totlabel.setText("TOTAL :-");

        btnins.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnins.setText("INSERT");
        btnins.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsActionPerformed(evt);
            }
        });

        btnrst.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnrst.setText("RESET");
        btnrst.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrstActionPerformed(evt);
            }
        });

        btnnew.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnnew.setText("NEW");
        btnnew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        total.setBackground(new java.awt.Color(255, 255, 255));
        total.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        total.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        total.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        total.setMaximumSize(new java.awt.Dimension(95, 27));
        total.setMinimumSize(new java.awt.Dimension(95, 27));
        total.setName("total"); // NOI18N
        total.setOpaque(true);
        total.setPreferredSize(new java.awt.Dimension(95, 27));

        btntot.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btntot.setText("CLICK HERE IF ALL MARKS ARE ENTERED");
        btntot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btntot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btndelete.setText("DELETE");
        btndelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnfetchall.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnfetchall.setText("FETCH All");
        btnfetchall.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnfetchall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfetchallMouseClicked(evt);
            }
        });
        btnfetchall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfetchallActionPerformed(evt);
            }
        });

        btnfetch.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnfetch.setText("FETCH");
        btnfetch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnfetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfetchActionPerformed(evt);
            }
        });

        btnmenu.setBackground(new java.awt.Color(52, 83, 168));
        btnmenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnmenu.setText("BACK TO MENU");
        btnmenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuMouseClicked(evt);
            }
        });
        btnmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuActionPerformed(evt);
            }
        });

        psfllabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        psfllabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        psfllabel.setText("PASS/FAIL");

        gradelabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        gradelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gradelabel.setText("GRADE :-");

        txtgrade.setEditable(false);
        txtgrade.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtgrade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgrade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgradeActionPerformed(evt);
            }
        });

        txtpsfl.setEditable(false);
        txtpsfl.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txtpsfl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpsfl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        txtpsfl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpsflActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtname))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtmts))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtroll))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txteng))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txthind))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtsci))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtsst)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(psfllabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtpsfl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(totlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(gradelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnins)
                                .addGap(32, 32, 32)
                                .addComponent(btndelete))
                            .addComponent(btnnew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnupdate)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnfetch)
                                .addGap(42, 42, 42)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnrst)
                            .addComponent(btnfetchall))
                        .addGap(55, 55, 55))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btntot, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txteng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txthind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtsst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtsci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(totlabel)
                        .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gradelabel)
                        .addComponent(psfllabel)
                        .addComponent(txtpsfl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtgrade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btntot)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnrst)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnins))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnew)
                    .addComponent(btnfetch)
                    .addComponent(btnfetchall))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsciActionPerformed

    private void txtsstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsstActionPerformed

    private void txtmtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmtsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmtsActionPerformed

    private void txthindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthindActionPerformed

    private void txtengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtengActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrollActionPerformed
        // TODO add your handling code here:        
    }//GEN-LAST:event_txtrollActionPerformed

    private void btninsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsActionPerformed
        // TODO add your handling code here:
                    
        try
        {
            System.out.println("gadha in try");
            //inser=conn.prepareStatement("insert into result (rno,name,english,hindi.maths,social,science)values(?,?,?,?,?,?,?)");
            //inser=conn.prepareStatement("insert into result (rno,name,english,hindi,maths,social,science)values(?,?,?,?,?,?,?)");
            inser=conn.prepareStatement("insert into results (rno,name,eng,hin,mat,soc,sci,total,grade,res) values(?,?,?,?,?,?,?,?,?,?)");
            System.out.println("bhaisa after prepare statement");
            
            String r=txtroll.getText();
            System.out.println(r);
            
            String n=txtname.getText();
            System.out.println(n);
            
            int e=Integer.parseInt(txteng.getText());
            System.out.println(e);
            
            int h=Integer.parseInt(txthind.getText());
            System.out.println(h);
            
            int m=Integer.parseInt(txtmts.getText());
            System.out.println(m);
            
            int ss=Integer.parseInt(txtsst.getText());
            System.out.println(ss);
            
            int s=Integer.parseInt(txtsci.getText());
            System.out.println(s);
            
            int t=tot;
            System.out.println(t);
            
            String g=txtgrade.getText();
            System.out.println(g);
            
            String re=txtpsfl.getText();
            System.out.println(re);
            
            
            inser.setString(1, r);
            inser.setString(2, n);
            inser.setInt(3, e);
            inser.setInt(4, h);
            inser.setInt(5, m);
            inser.setInt(6, ss);
            inser.setInt(7, s);
            inser.setInt(8, tot);
            inser.setString(9, gr);
            inser.setString(10, re);
            
            int count=inser.executeUpdate();
            if(count>0)
            {
                JOptionPane.showMessageDialog(null,"Sucessfully inserted ! ","Inserting into Table",JOptionPane.INFORMATION_MESSAGE );
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Cannot Insert ! ","Cannot Insert into Table",JOptionPane.ERROR_MESSAGE );
            }
            btnrstActionPerformed(null);
            inser.clearParameters();
            inser.close();
            System.out.println("Baila inside try");
        }
        catch(Exception ee)
        {
            System.out.println("Baila Exception");
            JOptionPane.showMessageDialog(this,ee.toString());
        }
       
    }//GEN-LAST:event_btninsActionPerformed

    private void btnrstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrstActionPerformed
        // TODO add your handling code here:
        try
        {
            txtroll.setText("");
            txtname.setText("");
            txteng.setText("");
            txthind.setText("");
            txtmts.setText("");
            txtsst.setText("");
            txtsci.setText("");
            total.setText("");
            txtgrade.setText("");
            txtpsfl.setText("");
        }
        catch(Exception ee)
        {
            JOptionPane.showMessageDialog(null, "Cannot Clear the fields",ee.toString() ,JOptionPane.ERROR_MESSAGE );
        }
    }//GEN-LAST:event_btnrstActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        btnrstActionPerformed(null);
    }//GEN-LAST:event_btnnewActionPerformed

    private void btntotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotActionPerformed
        // TODO add your handling code here:
        int a=0,b=0,c=0,d=0,e=0;
        a=Integer.parseInt(txteng.getText());
        b=Integer.parseInt(txthind.getText());
        c=Integer.parseInt(txtmts.getText());
        d=Integer.parseInt(txtsst.getText());
        e=Integer.parseInt(txtsci.getText());

        tot=a+b+c+d+e;
        total.setText(""+tot);
        System.out.println("total = "+tot);
        
        txtgradeActionPerformed(null);
        txtpsflActionPerformed(null);
    }//GEN-LAST:event_btntotActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        try
        {
            JOptionPane.showConfirmDialog(null,"input all the fields and then press the update button to update the database");
            modify=conn.prepareStatement("update results set rno=?,name=?,eng=?,hin=?,mat=?,soc=?,sci=?,total=?,grade=?,res=? where rno=?");
            String r=txtroll.getText();
            System.out.println(r);
            
            String n=txtname.getText();
            System.out.println(n);
            
            int e=Integer.parseInt(txteng.getText());
            System.out.println(e);
            
            int h=Integer.parseInt(txthind.getText());
            System.out.println(h);
            
            int m=Integer.parseInt(txtmts.getText());
            System.out.println(m);
            
            int ss=Integer.parseInt(txtsst.getText());
            System.out.println(ss);
            
            int s=Integer.parseInt(txtsci.getText());
            System.out.println(s);
            
            
            
            btntotActionPerformed(null);
            int t=tot;
            System.out.println(t);
            
            String g=txtgrade.getText();
            System.out.println(g);
            
            String re=txtpsfl.getText();
            System.out.println(re);
            
            modify.setString(1, r);
            modify.setString(2, n);
            modify.setInt(3, e);
            modify.setInt(4, h);
            modify.setInt(5, m);
            modify.setInt(6, ss);
            modify.setInt(7, s);
            modify.setInt(8,t);
            modify.setString(9, g);
            modify.setString(10, re);
            
            int count=modify.executeUpdate();
            if(count>0)
            {
                JOptionPane.showMessageDialog(null,"Sucessfully Updated ! ","Updating into the Table",JOptionPane.INFORMATION_MESSAGE );
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Cannot Update ! ","Cannot Update into Table",JOptionPane.ERROR_MESSAGE );
            }
            
            btnrstActionPerformed(null);
            modify.clearParameters();
            modify.close();
            btnfetchActionPerformed(null);
        }
        catch(Exception ee)
        {
            System.out.println("Baila Exception of update");
            JOptionPane.showMessageDialog(this,ee.toString());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            System.out.println("Gadha inside try");
            
            delete=conn.prepareStatement("delete from results where rno=?");
            
            System.out.println("Bhaisa after prepareStatement");
            
            String epn=txtroll.getText();
            delete.setString(1, epn);
            
            int cnt=delete.executeUpdate();
            
            if(cnt>1)
            
                JOptionPane.showMessageDialog(null, "Successfully Deleted The Record","Delete Window", JOptionPane.INFORMATION_MESSAGE);
            
            else
                JOptionPane.showMessageDialog(null, "Cannot Deleted The Record","Delete Window", JOptionPane.ERROR_MESSAGE);
            
            
            //delete.executeQuery();
            //JOptionPane.showMessageDialog(null,"Sucessfully Deleted The Record","Delete Window",JOptionPane.INFORMATION_MESSAGE);
            delete.close();
            btnrstActionPerformed(null);
            
        }
        catch(Exception ee)
        {
            System.out.println("Ghoda in Exception of delete");
            JOptionPane.showMessageDialog(this,ee.toString());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnfetchallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfetchallActionPerformed
        // TODO add your handling code here:
       /* try
        {
            System.out.println("Gadha inside the fetch try");
            
           res=fetch.executeQuery("Select * from results order by rno") ;
           
           String roll;         
           String name;
           int english;
           int hindi;
           int maths;
           int social;
           int science;
            
           DefaultTableModel tm=(DefaultTableModel)FetchAll.jTable1.getModel();
           
           while(true)
            {
                int c=tm.getRowCount();
                if(c==0)
                    break;
                else
                    tm.removeRow(0);
            }
            while(res.next())
            {
                roll=res.getString("rno");
                name=res.getString("name");
                english=res.getInt("eng");
                hindi=res.getInt("hin");
                maths=res.getInt("mat");
                social=res.getInt("soc");
                science=res.getInt("sci");
                Object kk[]={roll,name,english,hindi,maths,social,science};
                tm.addRow(kk);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error in connection"+e);
        }*/
        
        //li.setVisible(true);
    }//GEN-LAST:event_btnfetchallActionPerformed

    private void btnfetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfetchActionPerformed
        // TODO add your handling code here:
        try
        {
            String rn=txtroll.getText();
            
            fetch=conn.prepareStatement("Select * from results where rno=? ");
            
            fetch.setString(1, rn);
            fetch.executeQuery();
            res=fetch.getResultSet();
            res.next();
            txtname.setText(res.getString(2));
            txteng.setText(res.getString(3));
            txthind.setText(res.getString(4));
            txtmts.setText(res.getString(5));
            txtsci.setText(res.getString(6));
            txtsst.setText(res.getString(7));
            total.setText(res.getString(8));
            txtgrade.setText(res.getString(9));
            txtpsfl.setText(res.getString(10));
          
        }
        catch(Exception ee)
        {
            JOptionPane.showMessageDialog(this, ee.toString());
        }

    }//GEN-LAST:event_btnfetchActionPerformed

    private void btnfetchallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfetchallMouseClicked
        // TODO add your handling code here:
        new ListAll().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnfetchallMouseClicked

    private void btnmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmenuActionPerformed

    private void btnmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuMouseClicked
        // TODO add your handling code here:
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnmenuMouseClicked

    private void txtgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgradeActionPerformed
        // TODO add your handling code here:
        int per;
        per=(tot/5);
        System.out.println("percent="+per);
        
        if(per<59 && per>-1)
        {
            gr="F";
            txtgrade.setText(""+gr);
            System.out.println("Grade"+gr);
        }
        else if(per<70)
        {
            gr="D";
            txtgrade.setText(""+gr);
            System.out.println("Grade"+gr);
        }
        else if(per<80)
        {
            gr="C";
            txtgrade.setText(""+gr);
            System.out.println("Grade"+gr);
        }
        else if(per<90)
        {
            gr="B";
            txtgrade.setText(""+gr);
            System.out.println("Grade"+gr);
        }
        else if(per<101)
        {
            gr="A";
            txtgrade.setText(""+gr);
            System.out.println("Grade"+gr);
        }
        else
        {
            gr="";
            txtgrade.setText(""+gr);
            System.out.println("Grade nahi hai gadha"+gr);
        }
    }//GEN-LAST:event_txtgradeActionPerformed

    private void txtpsflActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpsflActionPerformed
        // TODO add your handling code here:
        String pf="";
        if(gr=="A"||gr=="B"||gr=="C"||gr=="D")
        {
            pf="PASS";
            txtpsfl.setText(""+pf);
            System.out.println("Result="+pf);
        }
        else
        {
            pf="FAIL";
            txtpsfl.setText(""+pf);
            System.out.println("Result="+pf);
        }
    }//GEN-LAST:event_txtpsflActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnfetch;
    private javax.swing.JButton btnfetchall;
    private javax.swing.JButton btnins;
    private javax.swing.JButton btnmenu;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnrst;
    private javax.swing.JButton btntot;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel gradelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel psfllabel;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totlabel;
    private javax.swing.JTextField txteng;
    private javax.swing.JTextField txtgrade;
    private javax.swing.JTextField txthind;
    private javax.swing.JTextField txtmts;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpsfl;
    private javax.swing.JTextField txtroll;
    private javax.swing.JTextField txtsci;
    private javax.swing.JTextField txtsst;
    // End of variables declaration//GEN-END:variables
}
